# Commands required to setup working docker enviro, link
# containers etc.
$setup = <<SCRIPT
# Stop and remove any existing containers
docker stop $(docker ps -a -q)
docker rm $(docker ps -a -q)

# Run and link the containers
docker run -d --name mariadb quay.io/nabinno/dove-ubuntu14-mariadb
# docker run -d --name mysql quay.io/nabinno/dove-ubuntu14-mysql
docker run -d --name postgres quay.io/nabinno/dove-centos7-postgresql
docker run -d --name mongodb quay.io/nabinno/dove-ubuntu14-mongodb
docker run -d --name redis quay.io/nabinno/dove-centos7-redis
docker run -d --name memcached quay.io/nabinno/dove-centos7-memcached
docker run -d --name rabbitmq quay.io/nabinno/dove-ubuntu14-rabbitmq
docker run -d --name nginx -p 80:80 quay.io/nabinno/dove-ubuntu14-nginx
docker run -d --name apps -p 3000:3000 -p 3001:3001 -p 4000:4000 -p 4001:4001 -p 8080:8080 -p 9000:9000 -p 49155:22 -v $(pwd):/home/centos --link redis:redis --link memcached:memcached --link nginx:nginx --link rabitmq:rabitmq --link postgres:postgres --link mariadb:mariadb --link mongodb:mongodb -P quay.io/nabinno/dove-ubuntu14-apps
SCRIPT

# Commands required to ensure correct docker containers
# are started when the vm is rebooted.
$start = <<SCRIPT
docker start mariadb
docker start postgres
docker start mongodb
docker start redis
docker start memcached
docker start rabbitmq
docker start nginx
docker start apps
SCRIPT

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure("2") do |config|

  # Setup resource requirements
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  # need a private network for NFS shares to work
  config.vm.network "private_network", ip: "192.168.33.10"

  # Rails Server Port Forwarding
  config.vm.network "forwarded_port", guest: 22, host: 49155, id: "ssh"
  config.vm.network "forwarded_port", guest: 80, host: 80, id: "http"
  config.vm.network "forwarded_port", guest: 3000, host: 3000
  config.vm.network "forwarded_port", guest: 3001, host: 3001
  config.vm.network "forwarded_port", guest: 4000, host: 4000
  config.vm.network "forwarded_port", guest: 4001, host: 4001
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 9000, host: 9000

  # Ubuntu
  config.vm.box = "ubuntu/trusty64"

  # Install latest docker
  config.vm.provision "docker"

  # Must use NFS for this otherwise rails
  # performance will be awful
  config.vm.synced_folder ".", "/app", type: "nfs"

  # Setup the containers when the VM is first
  # created
  config.vm.provision "shell", inline: $setup

  # Make sure the correct containers are running
  # every time we start the VM.
  config.vm.provision "shell", run: "always", inline: $start
end
